name: Update Font Tracer

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip3 install pyyaml requests

      - name: Run updater.py
        run: python3 updater.py ${{ secrets.GH_TOKEN }}

      - name: Commit changes
        run: |
          git config --local user.email "i@focuschen.com"
          git config --local user.name "Focus Chen"
          git remote set-url origin https://hifocus@github.com/zh-webfonts/webfonts.git
          git add -f font-tracer.yml
          git commit -m "Executed Font Tracer at $(date -u +'%Y-%m-%d %H:%M:%S')"
      - uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GH_TOKEN }}
          force: true
